name: Convert to PDF and Release

on:
  push:
    tags:
      - '*'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install puppeteer

    - name: Run conversion script
      run: |
          node -e "const fs = require('fs');
          const puppeteer = require('puppeteer');

          async function convertMarkdownToPDF(inputPath, outputPath) {
            const markdownContent = fs.readFileSync(inputPath, 'utf-8');

            const browser = await puppeteer.launch();
            const page = await browser.newPage();

            await page.setContent(markdownContent, { waitUntil: 'networkidle0' });

            const outputFileName = outputPath;
            await page.pdf({ path: outputFileName, format: 'A4' });

            await browser.close();
          }

          const inputFiles = ['syllabus.md', 'schedule.md'];  // Add more files as needed
          const outputFolder = 'pdf';

          for (const inputFile of inputFiles) {
            const outputFileName = \`\${outputFolder}/\${inputFile.replace(/\\.md$/, '.pdf')}\`;
            convertMarkdownToPDF(inputFile, outputFileName);
          }"

    - name: Upload PDF as Release Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-artifact
        path: ./pdf
