name: Convert to PDF and Release

on:
  push:
    tags:
      - '*'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up pandoc
      run: sudo apt-get install pandoc

    - name: Install pdflatex
      run: sudo apt-get install texlive-xetex

    - name: Install LaTeX packages
      run: sudo apt-get install texlive-fonts-recommended texlive-fonts-extra

    - name: Run pandoc
      run: pandoc -s ./readme.md -o ./pdf/readme.pdf --pdf-engine=xelatex

    - name: Upload PDF as Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: ./pdf/readme.pdf
